my_string=input("Я считаю символы, введите что нибудь: ")
print('В вашем тексте' , len(my_string) , 'символа(ов)' )
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])